leafIndex = "5"
commitment = "6280101244439376071439529182523330414942549839297035426992550869584774696950"

secret =  "136378054848304952389954076883343360994366129427947901736573628582321789406"

nullifier =  "136378054848304952389954076883343360994366129427947901736573628582321789406"

nullifier_hash =  "5417478993643498149970548561170513762617825883687142390740434973621080779060"
nullifier_hash_bytes32 =  "0x0bfa2f380b5f5932e47fd34c43b6033d4d5edfb5513550b7ba9bfcfbd5ff6934"

merkle_path = [
  "10500818963250585703507381350752932471923303914646640944634629156884748701889",
  "7423237065226347324353380772367382631490014989348495481811164164159255474657",
  "7489368939785492921843624421389675223101913269334845170464046301840329462398",
  "3607627140608796879659380071776844901612302623152076817094415224584923813162",
  "19712377064642672829441595136074946683621277828620209496774504837737984048981",
  "20775607673010627194014556968476266066927294572720319469184847051418138353016",
  "3396914609616007258851405644437304192397291162432396347162513310381425243293",
  "21551820661461729022865262380882070649935529853313286572328683688269863701601",
  "6573136701248752079028194407151022595060682063033565181951145966236778420039",
  "12413880268183407374852357075976609371175688755676981206018884971008854919922",
  "14271763308400718165336499097156975241954733520325982997864342600795471836726",
  "20066985985293572387227381049700832219069292839614107140851619262827735677018",
  "9394776414966240069580838672673694685292165040808226440647796406499139370960",
  "11331146992410411304059858900317123658895005918277453009197229807340014528524",
  "15819538789928229930262697811477882737253464456578333862691129291651619515538",
  "19217088683336594659449020493828377907203207941212636669271704950158751593251",
  "21035245323335827719745544373081896983162834604456827698288649288827293579666",
  "6939770416153240137322503476966641397417391950902474480970945462551409848591",
  "10941962436777715901943463195175331263348098796018438960955633645115732864202",
  "15019797232609675441998260052101280400536945603062888308240081994073687793470",
]

merkle_indices = [
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
]

root = "13274677166234267857973992309548755435658276785904043600754586732194174069857"
root_bytes32 = "0x1d593375ef11758f4dbd2cafd1d089ca413e259c65891cbd00b2966ac28fec61"